services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - '3306'
    ports:
      - '${MYSQL_LOCAL_PORT}:3306'
    volumes:
      - database-volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './apps/website:/usr/src/apps/website'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - './apps/website:/usr/src/apps/website'
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    user: ${LOCAL_USER}

volumes:
  database-volume:
